### ISSUE TITLE
Download the new CIL data and generate mp4 files

### ISSUE THREAD

**Issue by wawong** [CRBS/cildata_util#6]
**Background:**
We've been continuously adding new data into the current/old CIL last year. Therefore, we need to download those new data and generate the mp4 files as what we did last time.

**Technical details**
I added a new column, "processed_time"  to the "cil_data_type" table. For the new data, you need to use the following query to filter out the old data:
```
select * from cil_data_type where processed_time is null
```
Everything is the same as last time. We have only two tables, "cil_data_type" and "cil_download_status" to deal with. "cil_data_type" tells you about the image ids and the data types and then you report your results back to  "cil_download_status".
**Note**: Please download the new data to a new folder. So that, we don't need to move too much data around. And, we need to generate the mp4 files like last time.

**Comment by coleslaw481** [comment]
Since we are on the new CIL. I don't think this is needed. Closing ticket, please reopen if I am wrong.
