### ISSUE TITLE
Create a command line to generate thumbnails individually

### ISSUE THREAD

**Issue by wawong** [CRBS/cildata_util#8]
Sometimes, I find dark images on the website. It's not easy to detect them and convert them programmatically. I need a command line to do the following:

cildataconvert.py $jpg_image_path  $image_id  $outputfolder

The output should look like:
{$image_id}/{$image_id}_thumbnailx512.jpg
{$image_id}/{$image_id}_thumbnailx220.jpg
{$image_id}/{$image_id}_thumbnailx140.jpg 
{$image_id}/{$image_id}_thumbnailx88.jpg

**Comment by coleslaw481** [comment]
This has been completed.
